/**
 * THIS FILE IS AUTO-GENERATED by `convex dev`.
 * This stub allows TypeScript to compile before the first `convex dev` run.
 * The real file is generated from convex/schema.ts and will replace this.
 */
import type { AnyApi } from "convex/server";

export declare const api: AnyApi;
export declare const internal: AnyApi;
