/**
 * THIS FILE IS AUTO-GENERATED by `convex dev`.
 * This stub allows TypeScript to compile before the first `convex dev` run.
 * The real file is generated from convex/schema.ts and will replace this.
 */
import type { DataModelFromSchemaDefinition } from "convex/server";
import schema from "../schema.js";

export type DataModel = DataModelFromSchemaDefinition<typeof schema>;

export type Id<TableName extends string> = string & { __tableName: TableName };
