/**
 * THIS FILE IS AUTO-GENERATED by `convex dev`.
 * This stub allows TypeScript to compile before the first `convex dev` run.
 * The real file is generated from convex/schema.ts and will replace this.
 */
import type {
  MutationBuilder,
  QueryBuilder,
  ActionBuilder,
  GenericMutationCtx,
  GenericQueryCtx,
  GenericActionCtx,
} from "convex/server";
import type { DataModel } from "./dataModel.js";

export type MutationCtx = GenericMutationCtx<DataModel>;
export type QueryCtx = GenericQueryCtx<DataModel>;
export type ActionCtx = GenericActionCtx<DataModel>;

export declare const mutation: MutationBuilder<DataModel, "public">;
export declare const query: QueryBuilder<DataModel, "public">;
export declare const action: ActionBuilder<DataModel, "public">;
export declare const internalMutation: MutationBuilder<DataModel, "internal">;
export declare const internalQuery: QueryBuilder<DataModel, "internal">;
export declare const internalAction: ActionBuilder<DataModel, "internal">;
